name: deploy microservice
on: 
#  push:
#   branches:
#     - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploymentvars

    env:
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      VERSION: ${{ vars.VERSION }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./scripts/build-image.sh

      - name: Publish
        run: ./scripts/push-image.sh

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.30
      - name: Deploy
        run: ./scripts/deploy.sh

